nodes: 8
tasks_per_node: 8
tag: in1k-16f
eval_name: image_classification_frozen
resume_checkpoint: false
data:
  root_path: /opt/ml/code/MyDrive/jepa_images/
  image_folder: imagenet_full_size/061417/
  num_classes: 1
  resolution: 224
  dataset_name: ImageNet
optimization:
  num_epochs: 20
  batch_size: 16
  weight_decay: 0.001
  lr: 0.001
  start_lr: 0.001
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: true
pretrain:
  model_name: vit_large
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_sdpa: true
  use_silu: false
  tight_silu: false
  patch_size: 16
  folder: /opt/ml/code/MyDrive/
  checkpoint: vitl16.pth.tar
  write_tag: jepa
